/* 
  Practica 2 - Pipelines CI/CD en Jenkins con Docker y Groovy

*/
 
pipeline {
  // `agent any` = el pipeline se ejecuta en cualquier nodo/agente disponible.
  agent any

  stages {

    // ==========================
    // Practica 2 - Ejercicio 1
    // ==========================
    stage('Info') {
            steps {
                echo "Job: ${env.JOB_NAME}"
                echo "Build: ${env.BUILD_NUMBER}"
            }
        }

    // ==========================
    // Practica 2 - Ejercicio 3
    // ==========================
    stage('Build CI Image') {
      steps {
        script {
          // Construir imagen CI para ejecutar 'make link' y 'make test'
          // Nombre: 'java-imagen-ci'
          docker.build('java-imagen-ci', '-f devops/ci.Dockerfile .')
        }
      }
    }

    // ==========================
    // Practica 2 - Ejercicio 3
    // ==========================
    stage('Lint') {
      agent {
        docker {
          image 'java-imagen-ci'        
        }
      }
      steps {
        // Detecta errores de estilo
        sh 'make lint'
      }
    }

    // ==========================
    // Practica 2 - Ejercicio 3
    // ==========================
    stage('Test') {
      agent {
        docker {
          image 'java-imagen-ci'
        }
      }
      steps {
        // Detecta errores de test
        sh 'make test'
      }
    }
    
  }
}
