/* 
  Practica 2 - Pipelines CI/CD en Jenkins con Docker y Groovy

*/

// ==========================
// Practica 2 - Ejercicio 4
// ==========================
def runInDocker(String image, Closure body) {
    docker.image(image).inside {
        body()  
    }
}
 
pipeline {
  // `agent any` = el pipeline se ejecuta en cualquier nodo/agente disponible.
  agent any

  environment {
    // IMAGE_NAME
	  //IMAGE_NAME = "myapp:${env.BUILD_NUMBER}"
    // IMAGE REPO LOCAL
    IMAGE_REPO_LOCAL = 'scalian_training-java-hello-world'
    IMAGE_TAG  = "0.0.2"
  }

  stages {

    // ==========================
    // Practica 2 - Ejercicio 1
    // ==========================
    stage('Info') {
            steps {
                echo "Job: ${env.JOB_NAME}"
                echo "Build: ${env.BUILD_NUMBER}"
            }
    }

    // ==========================
    // Practica 2 - Ejercicio 3
    // ==========================
    stage('Build CI Image') {
      steps {
        script {
          // Construir imagen CI para ejecutar 'make link' y 'make test'
          // Nombre: 'java-imagen-ci'
          docker.build('java-imagen-ci', '-f devops/ci.Dockerfile .')
        }
      }
    }

    // =============================
    // Practica 2 - Ejercicio 3 - 4
    // =============================
    stage('Lint') {
      steps {
        script {
          runInDocker('java-imagen-ci') {
            // Detecta errores de estilo
            sh 'make lint'
          }
        }
      }
    }

    // =============================
    // Practica 2 - Ejercicio 3 - 4
    // =============================
    stage('Test') {
      steps {
        script {
          runInDocker('java-imagen-ci') {
            // Detecta errores de test
            sh 'make test'
          }
        }
      }
    }

    // =========================
    // Practica 2 - Ejercicio 5
    // =========================
    stage('Build image') {
      steps {
        script {
          def version   = "${IMAGE_REPO_LOCAL}:${IMAGE_TAG}"
          // Construye la imagen Docker usando el Dockerfile del repo
          docker.build("${version}", "--build-arg VERSION=${version} -f devops/Dockerfile .")
        }
      }
    }

    // ===============================
    // Practica 2 - Ejercicio 6 - 6.1
    // ===============================
    stage('CD') {
      when {
        anyOf {
          expression { return env.RUN_CD == 'true' }
          branch 'develop'
          branch 'master'
        }
      }
      steps {
        echo "CD habilitado: RUN_CD=${env.RUN_CD}, branch=${env.BRANCH_NAME}"

        // Levanta el contenedor definido en docker-compose.yml
        // Espera 5 segundos
        // Muestra los logs
        sh 'docker compose up -d'
        sh 'sleep 5'
        sh 'docker compose logs java_app'
      }
      post {
        always {
            // Elimina contenedor
            sh 'docker compose down --volumes'
        }
      }
    }
    
  }
}
